name: build-image

on:
  release:
    types: [published]
  push:
    # branches:
    #   - main

jobs:
  build-multi-go-multi-arch:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go_version:
          - "1.20"
          - "1.22"
          - "1.23"
          - "1.24"
        platforms:
          - linux/amd64
          - linux/arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     # Settings -> General -> Code and automation -> Environments -> New environment
      #     username: ${{ vars.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Determine image tags
        id: tags
        run: |
          GO_TAG=go${{ matrix.go_version }}
          PLATFORM_TAG="${GO_TAG}-${{ matrix.platforms }}"
          # 替换平台中的 `/` 为 `_`
          PLATFORM_TAG=$(echo "$PLATFORM_TAG" | tr '/' '_')
          echo "tags=$GO_TAG" >> $GITHUB_OUTPUT
          echo "platform_tag=$PLATFORM_TAG" >> $GITHUB_OUTPUT

      # group: login and push to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-arch image for Go ${{ matrix.go_version }} on ${{ matrix.platforms }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dockerfiles/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.tags.outputs.platform_tag }}
            ghcr.io/${{ github.repository }}:${{ steps.tags.outputs.tags }}
          build-args: |
            GO_VERSION=${{ matrix.go_version }}
          platforms: |
            ${{ matrix.platforms }}